name: Auto Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate timestamp
        id: timestamp
        run: echo "KOREAN_TIME=$(TZ='Asia/Seoul' date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_OUTPUT

      - name: Create Release Note Body
        id: release_body
        run: |
          cat << 'EOF' >> $GITHUB_OUTPUT
          RELEASE_BODY<<RELEASE_EOF
          ## PR Information

          **PR Link**: ${{ github.event.pull_request.html_url }}
          **PR Title**: ${{ github.event.pull_request.title }}
          **Author**: @${{ github.event.pull_request.user.login }}
          **Merged at**: ${{ steps.timestamp.outputs.KOREAN_TIME }}

          ## PR Description

          ${{ github.event.pull_request.body }}
          RELEASE_EOF
          EOF

      - name: Generate tag name
        id: tag
        run: |
          TAG_NAME="v$(TZ='Asia/Seoul' date +"%Y.%m.%d.%H.%M.%S")"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << 'NOTES_EOF' > release_notes.md
          ${{ steps.release_body.outputs.RELEASE_BODY }}
          NOTES_EOF
          gh release create "${{ steps.tag.outputs.TAG_NAME }}" \
            --title "${{ steps.timestamp.outputs.KOREAN_TIME }}" \
            --notes-file release_notes.md \
            --target ${{ github.sha }}
      - name: Delete assets
        run: |
          gh release delete-asset "${{ steps.tag.outputs.TAG_NAME }}" "release_test-${{ steps.tag.outputs.TAG_NAME }}.zip" -y
